<a href="https://colab.research.google.com/github/Mostafizur979/Artificial-Intelligence-Lab4/blob/main/AI_lab2_212_15_4130.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
a=np.array(([1,2,3],[4,5,6]))
print(type(a))
print(a.ndim)
print(a[0,1])

<class 'numpy.ndarray'>
2
2


In [ ]:
print(a)
print(a[:,0:2])

[[1 2 3]
 [4 5 6]]
[[1 2]
 [4 5]]


In [ ]:
arr=np.array([[1,2,3.3],[4,5,6]])
new_arr=arr.astype(int)
print(new_arr)

[[1 2 3]
 [4 5 6]]


In [ ]:
arr1=new_arr.copy()
arr1*=2
print(arr1)
print(new_arr)

[[ 4  8 12]
 [16 20 24]]
[[ 2  4  6]
 [ 8 10 12]]


In [ ]:
arr2=new_arr.view()
arr2*=2
print(arr1)
print(new_arr)


[[ 4  8 12]
 [16 20 24]]
[[ 4  8 12]
 [16 20 24]]


In [ ]:
print(arr1.base)
print(arr2.base)

None
[[ 4  8 12]
 [16 20 24]]


In [ ]:
print(arr2.shape)

(2, 3)


In [ ]:
arr3=arr2.reshape(3,2)
print(arr3)

[[ 4  8]
 [12 16]
 [20 24]]


In [ ]:
arr3=arr2.reshape(3,2,1)
print(arr3)

[[[ 4]
  [ 8]]

 [[12]
  [16]]

 [[20]
  [24]]]


In [ ]:
arr4=arr2.reshape(6,1)
print(arr4)

[[ 4]
 [ 8]
 [12]
 [16]
 [20]
 [24]]


In [ ]:
for i in arr2:
  print("row: ",i)

row:  [ 4  8 12]
row:  [16 20 24]


In [ ]:
for i in arr2:
  for x in i:
   print("element: ",x)

element:  4
element:  8
element:  12
element:  16
element:  20
element:  24


In [ ]:
arr1 = np.array([1,2,3,4])

arr2 = np.array([4, 5, 6])

arr = np.concatenate((arr1, arr2))

print(arr)

[1 2 3 4 4 5 6]


In [ ]:
arr1 = np.array([[1, 2],[3, 4],[5,6]])
arr2 = np.array([[5, 6], [7, 8],[9,10]])
arr = np.concatenate((arr1, arr2), axis=1)
print(arr)

[[ 1  2  5  6]
 [ 3  4  7  8]
 [ 5  6  9 10]]


In [ ]:
arr1 = np.array([[1, 2],[3, 4],[5,6]])
arr2 = np.array([[5, 6], [7, 8],[9,10]])
arr = np.concatenate((arr1, arr2), axis=0)
print(arr)

[[ 1  2]
 [ 3  4]
 [ 5  6]
 [ 5  6]
 [ 7  8]
 [ 9 10]]


In [ ]:

arr = np.array([1, 2, 3, 4, 5, 6])

newarr = np.array_split(arr, 4)

print(newarr[0])
print(newarr[1])
print(newarr[2])
print(newarr[3])

[1 2]
[3 4]
[5]
[6]


In [ ]:

arr = np.array([[1, 2], [3, 4], [5, 6], [7, 8], [9, 10], [11, 12],[13,14]])
newarr = np.array_split(arr, 4)
print(newarr[0])


[[1 2]
 [3 4]]


In [ ]:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8,9,11])
x = np.where(arr%2 == 1)
print(x)

(array([0, 2, 4, 6, 8, 9]),)


In [ ]:
arr = np.array([1,2,3,8,6,3])
x = np.searchsorted(arr, 7)
print(x)

3


In [ ]:
arr = np.array([[3, 2, 4], [5, 0, 1]])
print(np.sort(arr))

[[2 3 4]
 [0 1 5]]
